Series 데이터 생성 방법
[형식] pd.Series(data, index=인덱스)
 - data : Series로 만들 데이터 (딕셔너리, 리스트, 스칼라, numpy 배열)
 - index : 축 레이블의 리스트 / 0-Based index

1) 딕셔너리 이용한 Series 데이터 생성

In [ ]:
import pandas as pd
dic = {'name':['kim', 'lee', 'kang'], 'kor':[90, 85, 70], 'eng':[90, 75, 100]}
se_data = pd.Series(dic)
se_data

name    [kim, lee, kang]
kor         [90, 85, 70]
eng        [90, 75, 100]
dtype: object

2) numpy 배열을 이용한 데이터 생성

In [ ]:
import numpy as np
arr = np.array([80, 90, 70])
ser2_data = pd.Series(arr)
ser2_data

0    80
1    90
2    70
dtype: int64

DataFrame  생성 방법
[형식] pd.DataFrame(data, index=인덱스, columns=레이블 목록, dtype=데이터 타입)
- data : DataFrame으로 만들 데이터(딕셔너리, 리스트, 스칼라, numpy 배열, DataFrame 객체)
- index : 축(행)레이블의 리스트를 할당 / 인덱스 값이 없으면 0-Based index
- columns : 열 레이블의 리스트 할당 / 인덱스 값이 없으면 0-Based index
- dtype : column마다 데이터 유형을 명기함

1) numpy 배열을 이용한 생성

In [ ]:
arr = np.array([[80, 90, 70],[40, 50, 60]])
df = pd.DataFrame(arr)
df

    0   1   2
0  80  90  70
1  40  50  60

2) 딕셔너리를 이용한 생성

In [ ]:
dic = {'name':['kim', 'lee', 'kang'], 'kor':[90, 85, 70], 'eng':[90, 75, 100]}
df = pd.DataFrame(dic)
df

   name  kor  eng
0   kim   90   90
1   lee   85   75
2  kang   70  100

색인 객체의 생성 방법
[형식] index객체명=pd.Index(index list, dtype=None, name=None)
- index list : 인덱스 이름 목록
- dtype : 데이터의 유형 / None이면 가장 적합한 데이터 유형을 찾음
- name : 인덱스 객체의 이름

1) 색인 객체 만들기

In [ ]:
ind = pd.Index(['name','kor','eng'])
ind

Index(['name', 'kor', 'eng'], dtype='object')

2) Series 객체 생성

In [ ]:
se_data = pd.Series([['kim', 'lee', 'kang'], [80, 90, 50], [70, 60, 80]])
se_data

0    [kim, lee, kang]
1        [80, 90, 50]
2        [70, 60, 80]
dtype: object

3) 생성된 Series 객체에 색인 객체 할당

In [ ]:
se_data.index = ind
se_data

name    [kim, lee, kang]
kor         [80, 90, 50]
eng         [70, 60, 80]
dtype: object