◆ DataFrame 생성 방법  
1) pandas import

In [ ]:
import pandas as pd

2) pd.DataFrame(data, index=None, columns=None, dtype=None)

3) 데이터 타입

integer : int64
decimal : float64
string : object
boolean : bool
date & time : datetime64
category : category

4) 칼럼명만 지정하여 DataFrame 생성

In [ ]:
df = pd.DataFrame(data=[[10, 20], [30, 40], [50, 60]], columns=['c1', 'c2'])
df

   c1  c2
0  10  20
1  30  40
2  50  60

In [ ]:
# 칼럼명만 지정된 DataFrame에 인덱스명 추가하고 싶을 때
dic={'c1':[10, 30, 50], 'c2':[20, 40, 60]}
df = pd.DataFrame(dic, index=['kim', 'lee', 'kang'])
df

      c1  c2
kim   10  20
lee   30  40
kang  50  60

5) 인덱스명만 지정하여 DataFrame 생성

In [ ]:
df = pd.DataFrame(data=[[10, 20], [30, 40], [50, 60]], index=[1, 2, 3])
df

    0   1
1  10  20
2  30  40
3  50  60

6) 칼럼명, 인덱스명을 모두 지정하여 DataFrame 생성

In [ ]:
df = pd.DataFrame(data=[[10, 20], [30, 40], [50, 60]], index=[1, 2, 3], columns=['kor', 'eng'])
df

   kor  eng
1   10   20
2   30   40
3   50   60

◆ numpy를 이용한 DataFrame 생성방법

1) pandas와 numpy import

2) numpy를 이용하여 배열을 생성함

3) DataFrame 생성하기

In [ ]:
import numpy as np
arr = np.array([[10, 20], [30, 40], [50, 60]])
df = pd.DataFrame(arr, index = ['kim', 'lee', 'kang'], columns = ['kor', 'eng'])
df

      kor  eng
kim    10   20
lee    30   40
kang   50   60

◆ DataFrame을 df로 정의해서 사용

In [ ]:
from pandas import DataFrame as df

In [ ]:
arr = np.array([[10, 20], [30, 40]])
daf = df(arr)
daf

    0   1
0  10  20
1  30  40

◆ 딕셔너리를 이용한 DataFrame 생성

1) pandas import

2) 딕셔너리 정의

3) DataFrame 생성함

In [ ]:
dic=pd.DataFrame({'name':['kim','lee','kang'],'kor':[90,80,70],'eng':[40,50,60]})
daf = df(dic)
daf

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

◆ DataFrame에 행과 열 추가하기

1) 행 추가하기

DataFrame객체명.loc[새로운 행이름]=값 혹은 배열

In [ ]:
daf=pd.DataFrame({'name':['kim','lee','kang'],'kor':[90,80,70],'eng':[40,50,60]})
daf

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

▶ 이름 : song, 국어 : 95, 영어 : 80 인 행 추가

In [ ]:
daf.loc[3]=['song', 95, 80]
daf

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60
3  song   95   80

In [ ]:
daf.loc[0]=['park', 75, 70]
# 0번째 행에 덮어쓰기 됨
daf

   name  kor  eng
0  park   75   70
1   lee   80   50
2  kang   70   60
3  song   95   80

2) 열 추가하기

DataFrame객체명[새로운 열이름]=값 혹은 배열

▶ 수학점수 70,85,90을 추가하기

In [ ]:
daf['math']=[70, 85, 90, 70]
daf

   name  kor  eng  math
0  park   75   70    70
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

In [ ]:
daf.loc[0]=['kim', 90, 40, 70]
daf

   name  kor  eng  math
0   kim   90   40    70
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

◆ 행과 열 삭제하기

1) 행 삭제하기

DataFrame객체명.drop(행 인덱스 또는 배열, axis=0, inplace=True 또는 False)

- axis = 0 이면 행, 1이면 열

- inplace = True 이면 원 객체에 적용 / False이면 원 객체를 변경하지 않고 변경된 새로운 DataFrame 생성

In [ ]:
daf.drop(0, axis=0, inplace=False) # 원 객체가 변경되지 않음

   name  kor  eng  math
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

In [ ]:
daf

   name  kor  eng  math
0   kim   90   40    70
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

In [ ]:
daf.drop(0, axis=0, inplace=True) # 원 객체가 변경됨
daf

   name  kor  eng  math
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

2) 열 삭제하기

DataFrame객체명.drop(열 인덱스 또는 배열, axis=1, inplace=True 또는 False)

In [ ]:
daf.drop('math', axis=1, inplace=False)

   name  kor  eng
1   lee   80   50
2  kang   70   60
3  song   95   80

In [ ]:
daf

   name  kor  eng  math
1   lee   80   50    85
2  kang   70   60    90
3  song   95   80    70

◆ 행 선택하기

1) loc 를 이용한 행 선택

- 1개의 행 선택

DataFrame객체명.loc[선택할 행이름]

- 범위지정 선택

DataFrame객체명.loc[시작행이름:끝행이름]
=> 범위의 끝을 포함함

In [ ]:
df=pd.DataFrame({'name':['kim','lee','kang'],'kor':[90,80,70],'eng':[40,50,60]})
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

ex) 첫번째 행 선택

In [ ]:
first=df.loc[0]
first

name    kim
kor      90
eng      40
Name: 0, dtype: object

In [ ]:
first=df.loc[2]
first

name    kang
kor       70
eng       60
Name: 2, dtype: object

In [ ]:
df.loc[0:2]

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
two = df.loc[0:1]
two

  name  kor  eng
0  kim   90   40
1  lee   80   50

2) iloc를 이용한 행 선택

- 1개의 행 선택

DataFrame객체명.iloc[선택할 인덱스]

- 범위지정 선택

DataFrame객체명.iloc[시작인덱스:끝인덱스:슬라이싱간격]
=> 범위의 끝을 제외함 / 슬라이싱 간격은 생략할 수 있으며, 생략할 경우 1로 간주함
/ 슬라이싱 간격 -1로 지정하면 역순 제시 / 모든 행을 선택할 경우 시작인덱스와 끝인덱스 지정하지 않음

In [ ]:
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
df.iloc[1]

name    lee
kor      80
eng      50
Name: 1, dtype: object

In [ ]:
df.loc[0:2]   # loc : 0 ~ 2까지

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
df.iloc[0:2]   # iloc : 0 ~ 2 바로 앞(1)까지

  name  kor  eng
0  kim   90   40
1  lee   80   50

◆ 열 선택하기

1) 1개의 열 선택하기

DataFrame객체명[선택할 열이름]

2) 여러개 열 선택하기

DataFrame객체명[[선택할 열이름1, 선택할 열이름2....]]

ex)

df=pd.DataFrame({'name':['kim','lee','kang'],'kor':[90,80,70],'eng':[40,50,60]})

eng_data=df['eng']

name_eng_data=df[['name','eng']]

In [ ]:
df=pd.DataFrame({'name':['kim','lee','kang'],'kor':[90,80,70],'eng':[40,50,60]})
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
df['eng']

0    40
1    50
2    60
Name: eng, dtype: int64

In [ ]:
df[['eng', 'name']]   # 열 여러개 선택 시 대괄호 2개 필요

   eng  name
0   40   kim
1   50   lee
2   60  kang

◆ 원소 선택하기

1) loc를 이용한 원소 선택

DataFrame객체명.loc[행 인덱스 혹은 행명, 열 인덱스 혹은 열명]

2) iloc를 이용한 원소 선택

DataFrame객체명.iloc[행번호, 열번호]

In [ ]:
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
# 이름이 kim인 사람의 국어점수
df.loc[1, 'kor']   # loc는 행 열의 이름을 이용하여 선택

80

In [ ]:
# 이름이 kang인 사람의 국어점수
df.iloc[2, 1]   # iloc는 행 열의 번호를 이용하여 선택

70

3) iloc를 이용한 원소 선택

DataFrame객체명.iloc[행번호, 열번호]

In [ ]:
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
df.loc[0,'eng']

40

In [ ]:
df.iloc[0,2]

40

◆ 위치 변경하기

1) 행 위치 변경하기

DataFrame객체명.reindex(index=[인덱스 목록])

In [ ]:
df

   name  kor  eng
0   kim   90   40
1   lee   80   50
2  kang   70   60

In [ ]:
df=df.reindex(index=[2,0,1])
df

   name  kor  eng
2  kang   70   60
0   kim   90   40
1   lee   80   50

2) 열 위치 변경하기  => 대괄호 안에 원하는 순서대로 칼럼명 나열함

In [ ]:
df

   name  kor  eng
2  kang   70   60
0   kim   90   40
1   lee   80   50

In [ ]:
df[['eng', 'name', 'kor']]

   eng  name  kor
2   60  kang   70
0   40   kim   90
1   50   lee   80

In [ ]:
df

   name  kor  eng
2  kang   70   60
0   kim   90   40
1   lee   80   50

3) 행과 열 변경하기 => 전치행렬로 만들기

DataFrame객체명.transpose() 또는 DataFrame객체명.T

In [ ]:
df

   name  kor  eng
2  kang   70   60
0   kim   90   40
1   lee   80   50

In [ ]:
df.T

         2    0    1
name  kang  kim  lee
kor     70   90   80
eng     60   40   50